### ISSUE TITLE
fusermount: mount failed: Operation not permitted

### ISSUE THREAD

**Issue by maresb** [conda-forge/s3fs-fuse-feedstock#4]
I'm trying to mount a private S3 bucket from an EC2 instance. With both `v1.87` and `v1.89` I get
```
fusermount: mount failed: Operation not permitted
```
If I switch to [my build](https://github.com/maresb/docker-build-s3fs) then everything works.

I suspect that this feedstock is not compiling against the best libraries or something. I'll have to have a look when I find the time.

**Comment by maresb** [comment]
I don't know so well what I'm doing, but I figured it may be helpful to examine differences in `ldd` output between the broken conda-forge version and my working version.

Common libraries with the same versions:
```
        linux-vdso.so.1
        libfuse.so.2
        libcurl.so.4
        libxml2.so.2
        libcrypto.so.1.1
        libstdc++.so.6
        libpthread.so.0
        libc.so.6
        libdl.so.2
        libnghttp2.so.14
        libssl.so.1.1
        libgssapi_krb5.so.2
        libk5crypto.so.3
        libz.so.1
        liblzma.so.5
        libm.so.6
        /lib64/ld-linux-x86-64.so.2
        libgcc_s.so.1
        libkrb5.so.3
        libkrb5support.so.0
        libresolv.so.2
```
Common libraries with different versions:
```
    me: libicudata.so.66
    cf: libicudata.so.68

    me: libicuuc.so.66
    cf: libicuuc.so.68

    me: libssh.so.4
    cf: libssh2.so.1

    me: libcom_err.so.2
    cf: libcom_err.so.3
```
Only in conda-forge build:
```
        libiconv.so.2
        librt.so.1
```
Only in my build:
```
        libp11-kit.so.0
        libtasn1.so.6
        libkeyutils.so.1
        libheimntlm.so.0
        libkrb5.so.26
        libasn1.so.8
        libhcrypto.so.4
        libroken.so.18
        libffi.so.7
        libwind.so.0
        libheimbase.so.1
        libhx509.so.5
        libsqlite3.so.0
        libcrypt.so.1
        libpsl.so.5
        libidn2.so.0
        librtmp.so.1
        libldap_r-2.4.so.2
        liblber-2.4.so.2
        libbrotlidec.so.1
        libunistring.so.2
        libgnutls.so.30
        libhogweed.so.5
        libnettle.so.7
        libgmp.so.10
        libsasl2.so.2
        libgssapi.so.3
        libbrotlicommon.so.1
```
@xmnlab @esloch any ideas for how to proceed with diagnosing this?

**Comment by xmnlab** [comment]
@maresb when you run it with your build, are you using `sudo`?

**Comment by maresb** [comment]
@xmnlab no. The few times I have tested it with sudo it failed because it could not locate the credentials from my user account.

**Comment by xmnlab** [comment]
probably because when you use sudo it uses another environment. maybe sudo with `-E` could work ... but maybe it is not the point.

**Comment by maresb** [comment]
@xmnlab very cool trick with `sudo -E`! The mount succeeds.

Now I'm extremely puzzled. Why would conda-forge's `s3fs` have a permissions problem while my build does not?

**Comment by xmnlab** [comment]
wow ... it is very interesting. I am not sure why it is happening ...

**Comment by maresb** [comment]
@xmnlab I am running it from within a Docker container, so I wonder if that could have anything to do with it.

Maybe I should crosspost this issue to https://github.com/s3fs-fuse/s3fs-fuse.

**Comment by maresb** [comment]
Solved in https://github.com/conda-forge/libfuse-feedstock/issues/13
